FROM nginx:1.27-alpine

# remove default nginx site
RUN rm -rf /usr/share/nginx/html/*

# copy react build
COPY app/Frontend/todo/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx","-g","daemon off;"]
