# ---------- BUILD STAGE ----------
FROM node:20-alpine AS builder
WORKDIR /app

COPY app/Frontend/todo/package*.json ./
RUN npm install

COPY app/Frontend/todo/ .
RUN npm run build

# ---------- RUNTIME STAGE ----------
FROM nginx:1.27-alpine

RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx","-g","daemon off;"]
